kind: Service
apiVersion: v1
metadata:
  name: scopelens-website-service
  labels:
    app: website
    tier: frontend
  annotations:
    external-dns.alpha.kubernetes.io/hostname: <DOMAIN-NAME>
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: website
  type: LoadBalancer