apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    email: <EMAIL>
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-prod-account-key
    solvers:
    - selector:
        dnsZones:
          - "<DOMAIN-NAME>"
          - "*.<DOMAIN-NAME>"
      dns01:
        route53:
          region: ap-northeast-3
          hostedZoneID: <HOSTED-ZONE-ID> # optional, see policy above
          accessKeyID: <ACCESS-KEY-ID>
          secretAccessKeySecretRef:
            name: aws-credential
            key: secretKey
          role: arn:aws:iam::<ACCOUNT-ID>:role/<ROLENAME-OF-CERT-MANAGER>