kind: Deployment
apiVersion: apps/v1
metadata:
  name: scopelens-server-deployment
  labels:
    app: server
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
      version: v1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: server
        version: v1
    spec:
      #serviceAccountName: scopelens-server-account
      containers:
        - name: scopelens-server
          image: txfs19260817/scopelens-server:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8888
          resources:
            requests:
              memory: 512Mi
              cpu: 512m
            limits:
              memory: 768Mi
              cpu: 1024m
          env:
            - name: GIN_MODE
              value: release
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: INSTANCE_IP
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.podIP
          #securityContext:
          #  runAsUser: 1000
          volumeMounts:
            - name: server-config
              mountPath: "app/config"
              readOnly: true
      volumes:
        - name: server-config
          configMap:
            name: scopelens-server-config
            items:
              - key: "config.ini"
                path: "config.ini"